spring.application.name=tcs-ai-chatbox
server.port=8081
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.chat.observations.log-prompt=true
spring.ai.chat.client.enabled=false
spring.ai.chat.client.observations.log-prompt=true
logging.level.org.springframework.ai.chat.client.advisor=DEBUG
spring.ai.vectorstore.qdrant.collection-name=tcs-collection
spring.ai.vectorstore.qdrant.api-key=${QDRANT_API_KEY}
spring.ai.vectorstore.qdrant.host=392dfb50-e6f0-413a-9780-043a50ce86db.europe-west3-0.gcp.cloud.qdrant.io
spring.ai.vectorstore.qdrant.use-tls=true
spring.ai.vectorstore.qdrant.initialize-schema=true
spring.ai.google.genai.embedding.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.project-id=tcs-ai-chatbox
spring.ai.model.embedding=embedding-001
debug=true

